### ISSUE TITLE
Nix flake and/or package

### ISSUE THREAD

**Issue by t56k** [altsem/gitu#54]
Any interest in packaging this in a Nix flake and/or package? It would make it much easier than toolchaining Rust.

**Comment by altsem** [comment]
Most definitely. I'm unfamiliar with Nix myself though.

**Comment by t56k** [comment]
I've made a flake [here](https://github.com/t56k/gitu/) that builds on NixOS nicely--happy to run some tests on macOS too (and/or submit a PR).

**Comment by altsem** [comment]
Sweet, saw the PR, will have a look at it when I can.

I suppose I need an account somewhere to publish it? How does it work?

If anyone else into nix reads this, I'd appreciate if you had a look at the PR too :)

**Comment by musjj** [comment]
You just need to publish the `flake.nix` on the root of the repo, so no extra accounts are needed. But I think flakes are best paired with a binary cache, so that end users don't have to locally build the program.

A popular option for this is [Cachix](https://www.cachix.org). It's free for open-source projects, but you do need to [register an account](https://app.cachix.org/cache). There's this [tutorial](https://nix.dev/tutorials/nixos/continuous-integration-github-actions) on setting up a GitHub CI for it. There's also this [workflow](https://github.com/helix-editor/helix/blob/master/.github/workflows/cachix.yml) from Helix for reference. For the workflow to work, you need to store the `CACHIX_AUTH_TOKEN` secret you get after registering your project on Cachix.

I could make a separate PR for it, if it can't just be added to the one above. But really, you can just copy-paste Helix's workflow above and `%s/helix/gitu` (or the name you registered on Cachix).

**Comment by altsem** [comment]
@musjj thanks for the input, I'll give it a shot when this is merged

**Comment by evanrichter** [comment]
I already started maintaining the [upstream package in nixpkgs](https://github.com/NixOS/nixpkgs/blob/ddbd484a31481757a93d1ce7122dcb8469ff5fb2/pkgs/by-name/gi/gitu/package.nix)

a flake could still be useful for local development however

**Comment by evanrichter** [comment]
I guess another advantage of flakes is less delay between commit to package available

**Comment by altsem** [comment]
Nice! I take it the caching is less of an issue when developing locally

**Comment by t56k** [comment]
> Nice! I take it the caching is less of an issue when developing locally

The flake will cache dependencies locally--and build from `master` on update instead of waiting for nixpkgs. Both have their advantages. 

Keep in mind that my flake hasn't been tested on macOS yet, aiming to get that done shortly--unless someone just wants to run some tests and/or probably just add `darwin.apple_sdk.frameworks.Security` to the darwin-only `buildInputs`.

**Comment by t56k** [comment]
> > Nice! I take it the caching is less of an issue when developing locally
> 
> The flake will cache dependencies locally--and build from `master` on update instead of waiting for nixpkgs. Both have their advantages.
> 
> Keep in mind that my flake hasn't been tested on macOS yet, aiming to get that done shortly--unless someone just wants to run some tests and/or probably just add `darwin.apple_sdk.frameworks.Security` to the darwin-only `buildInputs`.

Updated with `Security` and `libiconv` to build on macOS.
