### ISSUE TITLE
Async git push, pull, fetch, etc

### ISSUE THREAD

**Issue by TheLostLambda** [altsem/gitu#97]
At some point, it might be nice to make the calls to `git push`, `git pull`, and `git fetch` (anything that relies on the network) asynchronous! I'm stuck on a quite slow connection, so when I go to push my changes, the UI freezes up for a while!

I could just wait to do all of my pushing at once (after staging and committing everything outstanding), but it might be a nice quality of life feature to decouple the UI responsiveness from network access!

**Comment by altsem** [comment]
This sounds reasonable! I realized things may become complicated, as you don't want to make the cursor move unexpectedly after e.g. a Pull.

I guess Fetch and Push are easier?

**Comment by TheLostLambda** [comment]
I agree there would have to be some thinking about where to place the cursor post-pull, but how is that currently done with reloading after pressing `g`?

I might still find it less jarring to have the cursor / view change post pull (it does when I press `g` already) than to have it hang during a pull, but perhaps I'm just not 100% understanding what you mean (I'm sure there is more nuance on the code-side)!

**Comment by altsem** [comment]
There's two aspects I think.
1. the cursor might move unexpectedly on a refresh
2. A refresh might happen unexpectedly

Point 1. already happens. Gitu is pretty dumb about this, but it seems fine due to how 2. never happens. A refresh only happens after a command is executed, or a g is pressed.

For example, if a Pull happened async:
1. I press 'Fp'.
2. The pop up shows at the bottom:
`$ git pull`

Currently:
3. Everything is blocked until the command finishes.
4. The view is refreshed
5. The popup will close as a press a key

3. The command is running in the background
4. I might decide I want to delete an untracked file, so I move the cursor to it
5. The Pull finishes and a refresh happens, yanking the cursor to something I did not intend to delete.
6. Before I can react, I press `K`

**Comment by altsem** [comment]
@TheLostLambda I implemented this (I think) :)
I'll leave it on this PR for a while in case you or anyone like to test it out, or have any input.
#108

**Comment by TheLostLambda** [comment]
Exciting! I'll take a look and kick the tires!
